---

- name: "Validate discovery"
  shell: "ping -c 1 {{ item }}"
  register: item_reachable
  failed_when: item_reachable.rc > 0
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ inventory_hostname + '.node.consul' }}"
