---
galaxy_info:
  author: Louis Gueye
  description: An Ansible role to create consul credentials (gossip encryption key, tls certificate authority, tls servers certificates, tls client certificates)
