---
# Safe to locally store secrets for that playbook
# This folder will NEVER be uploaded in the repository
# A better alternative is to create a vpn server which acts as a bastion.
safe_dir: "{{ lookup('ansible.builtin.env', 'HOME') + '/.distributed-platform-playground/safe' }}"
safe_ssh_dir: "{{ safe_dir }}/ssh"
safe_discovery_dir: "{{ safe_dir }}/discovery"

# Connectivity roles
# The main objective of this role is to automate connectivity
# We first create an ssh keypair in the safe which will be reused for the automation user
# Then, as root, we create the automation user + group
# Then, still as root, we configure the automation group as sudoer
# Then, still as root, we add the public key created in the safe, in the authorized key of the remotely created automation user
# That way, when we execute the ansible playbooks as automation, and provide the ssh private key to ansible, the automation user will be automatically logged in without prompt and will be able to perform ansible admin tasks as if it was a root user
# Finally, we validate the connectivity by logging in all servers as automation
# We're now ready to run all subsequent playbooks as automation rather than root or any human account

# sudo users group name
sudoers_group: 'automation'
# list of sudo users
sudoers:
  - 'automation'

# Common
service_startup_timeout: 60

# discovery
architecture_map:
  amd64: 'amd64'
  x86_64: 'amd64'
  armv6l: 'arm'
  armv7l: 'arm'
  aarch64: 'arm64'
  32-bit: '386'
  64-bit: 'amd64'
os_architecture: "{{ architecture_map[ansible_architecture] }}"
os_family: "{{ ansible_system | lower }}"

consul_version: '1.20.1-1'

consul_os_packages: ['unzip']
consul_checksum_file_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version}}_SHA256SUMS"
consul_pkg: "consul_{{ consul_version }}_{{ os_family }}_{{ os_architecture }}"
consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_pkg }}.zip"
consul_download_dir: '/tmp/consul/credentials'

consul_ports:
  dns: "{{ consul_ports_dns | default('8600', true) }}"
  http: "{{ consul_ports_http | default('8500', true) }}"
  https: "{{ consul_ports_https | default('-1', true) }}"
  rpc: "{{ consul_ports_rpc | default('8400', true) }}"
  serf_lan: "{{ consul_ports_serf_lan | default('8301', true) }}"
  serf_wan: "{{ consul_ports_serf_wan | default('8302', true) }}"
  server: "{{ consul_ports_server | default('8300', true) }}"

